### ISSUE TITLE
Errors about resources not found when starting the app

### ISSUE THREAD

**Issue by Artur-** [vaadin/skeleton-starter-flow-spring#55] opened 2018-03-05 21:01 UTC
```
2018-03-05 22:55:59.085  INFO 15182 --- [nio-8080-exec-1] c.v.f.c.internal.HtmlDependencyParser    : Can't find resource 'src/example-template.html' via the servlet context
2018-03-05 22:55:59.136  INFO 15182 --- [nio-8080-exec-1] c.v.f.c.internal.HtmlDependencyParser    : Can't find resource 'styles/shared-styles.html' via the servlet context
```

Why is that even INFO? It does not provide me with any info about the implications (there are seemingly none?) or what I should do

**Comment by pleku** [comment] 2018-03-05 21:03
Duplicate of https://github.com/vaadin/flow/issues/3640

**Closed by pleku** 2018-03-05 21:03 UTC
