### ISSUE TITLE
Spring Boot devtools reload is broken with Vaadin 13

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/skeleton-starter-flow-spring#131] opened 2019-03-19 15:21 UTC
**Setup:** 
Starter downloaded from vaadin.com/start, `vaadin.version`=13.0.1
Java 11

**App**
```
@Route
public class MainView extends VerticalLayout {

    public MainView() {
        add(new H1("hello world"));
    }
}
```

**Problem description**
Changing the app, `Hello world` -> `Hello foo` reloads OK once. On subsequent changes, the browser shows the following error message:
```
Could not navigate to ''
Reason: Couldn't find route for ''

Available routes:
This detailed message is only shown when running in development mode.
```
**This error message persists even if you restart the server.** 

The only way to get rid of the error message that I could find was to clear the browser cookies.

**Comment by ZheSun88** [comment] 2019-03-22 11:53
It looks this is a bug when run the project with Java 11 only. I could not reproduce it with JDK 1.8.

**Comment by pleku** [comment] 2019-12-17 07:41
We should take a look at this after vaadin/flow#7068 to make sure that there is no Java 11 specific issues

**Comment by denis-anisimov** [comment] 2019-12-18 10:09
I can't reproduce this with the latest `14.1.2` Platform skeleton starter flow.
I use Java 11 JDK 11.0.3.

@marcushellberg , could you please check the latest starter version?

**Comment by joheriks** [comment] 2019-12-18 13:43
Second that. Seems to work well with `14.1.2` when adding, renaming and removing routes.
https://github.com/vaadin/flow/issues/7070#issuecomment-567021605

**Comment by joheriks** [comment] 2019-12-19 08:42
Closing this as no longer is reproducible.

**Closed by joheriks** 2019-12-19 08:42 UTC
Labels: Java 11, bug, spring
